// <auto-generated />
using System;
using IntelligenceQueryEngine.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IntelligenceQueryEngine.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260423172557_int")]
    partial class @int
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.15");

            modelBuilder.Entity("IntelligenceQueryEngine.Models.Profile", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<int>("age")
                        .HasColumnType("INTEGER")
                        .HasColumnName("age");

                    b.Property<string>("age_group")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("age_group");

                    b.Property<string>("country_id")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("country_id");

                    b.Property<string>("country_name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("country_name");

                    b.Property<double>("country_probability")
                        .HasColumnType("REAL")
                        .HasColumnName("country_probability");

                    b.Property<DateTime>("created_at")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("gender")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("gender");

                    b.Property<double>("gender_probability")
                        .HasColumnType("REAL")
                        .HasColumnName("gender_probability");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("id");

                    b.HasIndex("name")
                        .IsUnique();

                    b.ToTable("profiles");
                });
#pragma warning restore 612, 618
        }
    }
}
